### ISSUE TITLE
Cannot Deserialize fails for DaemonSet with no containers list

### ISSUE THREAD

**Issue by nightkr** [Arnavion/k8s-openapi#110]
Basically, it's possible to create a DaemonSet where `spec.template.spec.containers` is `null` (the current serialization code will do this if `containers` is empty). Trying to deserialize the object from the server will then fail, since `null` is not a valid value for a `Vec<Container>`.

I think the root problem here is that the server-side validation here happens when creating/updating a `Pod`, but the `PodSpec` binding is generated with the assumption that validation has already been performed.

**Comment by Arnavion** [comment]
```rust
let daemon_set = k8s_openapi::api::apps::v1::DaemonSet {
	spec: Some(k8s_openapi::api::apps::v1::DaemonSetSpec {
		template: k8s_openapi::api::core::v1::PodTemplateSpec {
			spec: Some(k8s_openapi::api::core::v1::PodSpec {
				..Default::default()
			}),
			..Default::default()
		},
		..Default::default()
	}),
	..Default::default()
};
println!("{}", serde_json::to_string(&daemon_set).unwrap());
```

```
{"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{},"spec":{"selector":{},"template":{"spec":{"containers":[]}}}}
```

But anyway, we can have Deserialize be more lenient.
