### ISSUE TITLE
VolumeSnapshot and friends?

### ISSUE THREAD

**Issue by thedodd** [Arnavion/k8s-openapi#127]
Reviewing the docs, it does not appear as though we have generated models for the `VolumeSnapshot` `snapshot.storage.k8s.io/v1` type and other similar resources. Am I looking in the wrong location, or is there something blocking these types from being generated?

**Comment by Arnavion** [comment]
There's no such type in https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

**Comment by thedodd** [comment]
So, looks like these objects are still in the from of CRDs. I was under the impression that these objects had been added to the internal k8s resources types, but I was incorrect.
- https://github.com/kubernetes-csi/external-snapshotter/blob/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
- https://github.com/kubernetes-csi/external-snapshotter/blob/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

As such, I will need to work with these CRDs in a slightly different way then. Thank you.
