### ISSUE TITLE
release with v1.27

### ISSUE THREAD

**Issue by casualjim** [Arnavion/k8s-openapi#143]
Would it be possible to publish a version that has the 1.27 API included?

I'd like to implement the new [watch-list](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/3157-watch-list/README.md) support in kube-rs as it's critical for us.

**Comment by Arnavion** [comment]
Can you implement it against k8s-openapi master and make sure everything is correct? I want to be sure the changes I made to `WatchEvent`, ie adding `annotations` to `WatchEvent::Bookmark`, is correct and sufficient.

**Comment by Arnavion** [comment]
I saw that you've made https://github.com/kube-rs/kube/pull/1255 . Let me know when kube is satisfied with it and they're sure that everything is fine from the k8s-openapi side, and I'll cut a release.

**Comment by Arnavion** [comment]
Released v0.19.0
