### ISSUE TITLE
Looking for example on how to use k8s_openapi::api::core::v1::Event::create function

### ISSUE THREAD

**Issue by drwill-ms** [Arnavion/k8s-openapi#146]
I see the method definition at <https://docs.rs/k8s-openapi/latest/k8s_openapi/api/core/v1/struct.Event.html#method.create>, but I'm new to Rust and this library; I'm having a hard time getting the code to work. I went looking for a test or a sample in this repo but couldn't find one. Can you point me to an example?

Thanks so much! :)

**Comment by Arnavion** [comment]
See https://docs.rs/k8s-openapi/latest/k8s_openapi/index.html

Tests are in https://github.com/Arnavion/k8s-openapi/tree/master/k8s-openapi-tests if you really want to use the API methods. But almost everyone ignores the API methods and uses `kube` instead.
