### ISSUE TITLE
Plans to Support Builder Pattern in Kube.rs?

### ISSUE THREAD

**Issue by Oyelowo** [Arnavion/k8s-openapi#156]
I’ve been exploring the k8s-openapi library and find it incredibly useful for interfacing with Kubernetes in Rust. However, I noticed that the library does not currently support the builder pattern through libraries like `typed-builder` or `derive_builder`, which can enhance the usability and type safety of building complex objects.

From my research across GitHub issues, I haven’t found any discussions or plans to implement this feature. Here are my questions:

Is there a specific reason why the builder pattern isn’t currently supported in `k8s-openapi`? Understanding any underlying architectural or design considerations could provide valuable insights.

Are there any plans to support the builder pattern in future releases? If not, could this be considered a valuable addition to the roadmap? The builder pattern can significantly ease the creation of objects with many optional parameters, which is common in Kubernetes configurations.

How can the community contribute to such a feature? If there is interest in having builder pattern support, I would love to explore how I can contribute to the implementation.

**Comment by Arnavion** [comment]
>From my research across GitHub issues, I haven’t found any discussions or plans to implement this feature.

https://github.com/Arnavion/k8s-openapi/issues?q=is%3Aissue+builder -> https://github.com/Arnavion/k8s-openapi/issues/80 :)

**Comment by Oyelowo** [comment]
Just checked out #80 after your mention-thanks for pointing me there! I’ve caught up on the discussion now. Nothing to add at the moment, just wanted to see what had been covered. Also, thanks for all the work you’ve put into this project; it’s really appreciated!

**Comment by imp** [comment]
@Oyelowo you may want to have a look at https://docs.rs/k8s-openapi-ext
