### ISSUE TITLE
Patch struct causes errors when making requests

### ISSUE THREAD

**Issue by JoshMock** [Arnavion/k8s-openapi#43]
I was trying to use the [`Patch` struct](https://docs.rs/k8s-openapi/0.4.0/k8s_openapi/apimachinery/pkg/apis/meta/v1/struct.Patch.html) to run [`patch_namespaced_ingress`](https://docs.rs/k8s-openapi/0.4.0/k8s_openapi/api/extensions/v1beta1/struct.Ingress.html#method.patch_namespaced_ingress), but it appears based on both the documentation and the code that the only valid value of `body` is an empty struct reference `&Patch{}`.

When I do that, I get the following error at run time:
```
thread 'main' panicked at 'failed to patch ingress: ErrorMessage { msg: "Invalid method: PATCH" }
```

This is likely because the JSON body on the API request needs values in the form of a [JSON merge patch](https://tools.ietf.org/html/rfc7386), eg:
```json
{
    "op" : "replace" ,
    "path" : "/some/path",
    "value" : "foo"
}
```

At first I thought this was me being new to Rust and just missing how to do pass the `body` parameter correctly, like maybe I needed to build a JSON body with Serde and cast it to a `Patch` struct. But then I showed my issue to another developer and they came to the same conclusion.

I'm using the `v1_11` feature, for what it's worth. If there's any other information I can provide to clarify what I'm seeing, let me know! Thanks for building this!

**Comment by Arnavion** [comment]
This was fixed in https://github.com/Arnavion/k8s-openapi/commit/79185b336c8666f71e049e82c1500066b338fb3c It'll be in 0.5.0

**Comment by Arnavion** [comment]
As a workaround until then, you can take the `http::Request<Vec<u8>>` that you get from `Ingress::patch_namespaced_ingress` and replace its body with a stringified `serde_json::Value` of your choice.

**Comment by JoshMock** [comment]
Thank you @Arnavion! I'll give this a shot.

**Comment by Arnavion** [comment]
Note that you'll also need to set the `Content-Type` header to one of `application/json-patch+json`, `application/merge-patch+json` or `application/strategic-merge-patch+json` depending on what type of patch you're sending.

---

These are listed in the spec but I can't think of a way to easily surface this choice to the API user. Maybe something like

```diff,rust
-struct Patch(serde_json::Value);
+enum Patch {
+    Json(serde_json::Value),
+    Merge(serde_json::Value),
+    StrategicMerge(serde_json::Value),
+}
```

and then have every API operation that takes a `&Patch` have special codegen.

It does look like patch operations are the only place where this kind of `Content-Type` choice matters, and it's always these three types, so it doesn't seem like a bad idea to have special codegen for it...

**Comment by Arnavion** [comment]
With 36334e61f3384aa2f44a52ee5e5064bca8a775dc, `Patch` is now emitted as the enum I showed above, and all operations set the `Content-Type` header in the generated request.
