### ISSUE TITLE
Self-host docs

### ISSUE THREAD

**Issue by Arnavion** [Arnavion/k8s-openapi#57]
docs.rs [released a broken update, admits the update wasn't properly tested in the first place, is unwilling to revert to the working version, and is in no rush to fix the current version.](https://github.com/rust-lang/docs.rs/issues/422) So `k8s-openapi-derive` 0.6.0 [still has no docs.](https://docs.rs/crate/k8s-openapi-derive/0.6.0)

Let's host our own docs for `k8s-openapi` and `k8s-openapi-derive`

**Comment by theypsilon** [comment]
It's quite frustrating indeed.

I found a temporary solution for my proc macro crate. You have to publish a version of your crate with a different name, and then publish another create with the good package name that reexports your macros removing the proc_macro = true from your Cargo.toml,

Example: https://github.com/theypsilon/arraygen/blob/docfix/src/lib.rs
