### ISSUE TITLE
Does the Metadata trait need to depend on Resource?

### ISSUE THREAD

**Issue by clux** [Arnavion/k8s-openapi#61]
As far as I can tell from [the docs on the `Metadata`](https://arnavion.github.io/k8s-openapi/v0.7.x/k8s_openapi/trait.Metadata.html), the impls do not seem to require the associated constants from `Resource`.

I have a two part generic `Object<Spec, Status>` that I would like to implement `Metadata` for, but am unable to, because it forces me to `impl Resource for` it, and that information is propagated down later.

**Comment by Arnavion** [comment]
As the docs say:

- `Resource`: "A trait applied to all Kubernetes resources."

- `Metadata`: "A trait applied to all Kubernetes resources that have metadata."

I don't understand how "that information is propagated down later" will help you, given that implementing a trait like `Resource` is a type-system concern, not something you do dynamically. ie there is no "later".

(We can continue the discussion in https://github.com/clux/kube-rs/pull/157 )

**Comment by clux** [comment]
> I don't understand how "that information is propagated down later" will help you, given that implementing a trait like `Resource` is a type-system concern, not something you do dynamically. ie there is no "later".

Crap, you're right I'm sorry. Will need to look at a `derive` based setup instead instead of keeping this abstraction.
