### ISSUE TITLE
MicroTime should use microsecond percision in serialization

### ISSUE THREAD

**Issue by peterhuene** [Arnavion/k8s-openapi#63]
See related issue in deislabs/krustlet#5.

It appears that the serialization of `MicroTime` may result in 3, 6, or 9 digits for the subsecond precision.

I believe this is because it simply serializes the inner `DateTime<Utc>`, which will format as if `to_rfc3339` was called;  I believe this behaves as if it were being formatted with `SecondsFormat::AutoSi` resulting in 3, 6, or 9 digits depending on the nanoseconds value in the `DateTime`.

Unfortunately, k8s appears to require exactly six digits of subsecond precision and will error when parsing the datetimes containing 3 or 9 digits of precision.

I think the fix here would be to change `MicroTime`'s serialization such that it serializes the result of `self.0.to_rfc3339(SecondsFormat::Micro, true)`.  This should guarantee six digits of subsecond precision.

**Comment by Arnavion** [comment]
Never mind, it's basically the same amount of work to special-case it for `MicroTime` as for both `Time` and `MicroTime`. Also, I confirmed that even if Kubernetes might accept decimals in `Time` serialized form, it definitely doesn't emit them. So just to be safe, I'm going to truncate `Time` to zero decimals as well.

**Comment by Arnavion** [comment]
@technosophos The question was about `Time`, not `MicroTime`, but as I said in the comment right before yours it doesn't matter any more.

**Comment by Arnavion** [comment]
Can either of you test with [the `fix-63 branch`](https://github.com/Arnavion/k8s-openapi/compare/fix-63) ? It should be a drop-in replacement for `k8s-openapi = "0.7"`

**Comment by peterhuene** [comment]
I'll test it now.

**Comment by peterhuene** [comment]
Unfortunately it looks like `krustlet` is a little out of date wrt `kube` and `k8s-openapi` versions, and there's been breaking changes in `kube` since the version it is currently using, so it'll take longer for me to test out (I just started with `krustlet` today).

**Comment by Arnavion** [comment]
You can manually edit the `time.rs` and `micro_time.rs` in your `~/.cargo/registry/src/github.com-*/k8s-openapi-*/...` path with the changes from that branch.

**Comment by technosophos** [comment]
I just created a quick project using the latest version, and tested the `MicroTime` fix, and it is looking good. I am now definitely seeing timestamps with trailing zeros.

**Comment by peterhuene** [comment]
I tested with just the change to `MicroTime` and 👍

**Comment by technosophos** [comment]
@Arnavion Thank you _so much_ for going out of your way to fix this so quickly. I really, really appreciate that.

**Comment by radu-matei** [comment]
> Unfortunately it looks like `krustlet` is a little out of date wrt `kube` and `k8s-openapi` versions.

There is a [work in progress branch](https://github.com/deislabs/krustlet/pull/40) that updates to the latest release.
