### ISSUE TITLE
v1.20 feature missing from the 0.10.0 release?

### ISSUE THREAD

**Issue by jiayihu** [Arnavion/k8s-openapi#84]
I can clearly see the feature `v1_20` there in the Cargo.toml but if try to use it it's not available from the package in crates.io

lib.rs is more explicit in showing that actually the feature is not listed in the published crate: https://lib.rs/crates/k8s-openapi

**Comment by Arnavion** [comment]
https://github.com/Arnavion/k8s-openapi/blob/v0.10.0/Cargo.toml#L47-L55

**Comment by jiayihu** [comment]
So this was on purpose, it's just master that has v1_20 but it's still at version 0.10.0

**Comment by Arnavion** [comment]
Yes, I bump the versions in the manifests before a release, not after.
