### ISSUE TITLE
New k8s-openapi drop (post 0.11.0)

### ISSUE THREAD

**Issue by imp** [Arnavion/k8s-openapi#99]
Is there any chance for a fresh release? There are changes accumulated in the repo after the 0.11.0 release (1.21 support, etc) that are needed in other places and it will be helpful to have them from `crates.io`.
Keep up the good job!

**Comment by Arnavion** [comment]
I just need to make time to finish up https://github.com/Arnavion/k8s-openapi/pull/98 at least. $dayjob has been taking all my time.

**Comment by Arnavion** [comment]
https://crates.io/crates/k8s-openapi/0.12.0
